### ISSUE TITLE
User Guide and Examples updates.

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/BridgesUNCC.github.io#18]
I have done a first round of updates to the User guide and tutorials to reflect the current version of BRIDGES. We now have (thanks to Dakota) live examples as part of the user guide. 

I have also added documentation pages to the AVLTreeElement, these need some work (I have put comments in that page - mainly to get the live examples working for both and also update hte C++ example to correspond to the Java example I created) -- Dakota, you should do that and it shouldnt take very long.

Also added simple class diagrams for each Bridges Element and updated our obsolete(and incorrect)  figure in the Overview  page.

Comments/suggestions are welcome. The new pages should now be visible from  the Documentation link of BRIDGES.

**Comment by dcarmer** [comment]
I should have it done this weekend.

Also you mentioned the "incorrect" figure in the overview page. Since I updated when I created the guide not too long ago, I assume you considered it incorrect because it showed DLelement as inheriting from SLelement. This is in fact the way the C++ version is organized, and how I believe the Java version should also be structured. If there is a good reason not to have DLelement inherit from SLelement please let me know.

Either way, the diagram should be updated again for the inclusion of the generic Tree class and the BTree taking its old spot as a binary tree. Also some of the diagrams images you put up for the elements include your cursor, red misspelling underlines and highlighted selections. I'll fix these at the  same time as I update the AVL page.

**Comment by krs-world** [comment]
Ok, I can modify the figure -- I didnt realize the class hierarchy was 
different in C++. I will take a look at that

again. I have the figure files (in keynote) so I can easily update those 
- dont worry about those.  We wil, however,

need to modfiy the Java doubly linked list class(Java version), though.

     -- krs


On 6/15/16 2:33 AM, Dakota Carmer wrote:
>
> I should have it done this weekend.
>
> Also you mentioned the "incorrect" figure in the overview page. Since 
> I updated when I created the guide not too long ago, I assume you 
> considered it incorrect because it showed DLelement as inheriting from 
> SLelement. This is in fact the way the C++ version is organized, and 
> how I believe the Java version should also be structured. If there is 
> a good reason not to have DLelement inherit from SLelement please let 
> me know.
>
> Either way, the diagram should be updated again for the inclusion of 
> the generic Tree class and the BTree taking its old spot as a binary 
> tree. Also some of the diagrams images you put up for the elements 
> include your cursor, red misspelling underlines and highlighted 
> selections. I'll fix these at the same time as I update the AVL page.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/BridgesUNCC/BridgesUNCC.github.io/issues/18#issuecomment-226100151>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFZSOBz9T8_rnwZr1KgfuHbxqZ0qE7l1ks5qL5zVgaJpZM4I1lSm>.
>

-- 
Kalpathi Subramanian                                   Ph: 704 687 8579
Associate Professor                                    Email: krs@uncc.edu
Dept of Computer Science                               Web:http://webpages.uncc.edu/~krs
The University of North Carolina
Charlotte, NC 28202-0001

**Comment by esaule** [comment]
@krs-world is this done?
